### ISSUE TITLE
cmake error ( OpenCVConfig.cmake, opencv-config.cmake)

### ISSUE THREAD

**Issue by tempdeltavalue** [ryouchinsa/sam-cpp-macos#1]
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:4 (find_package):
  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
If you are using the macOS device, please install opencv.
`brew install opencv`

**Comment by tempdeltavalue** [comment]
tempdeltavalue@Ms-MacBook-Pro sam-cpp-macos % cmake --build build

[ 25%] Building CXX object CMakeFiles/sam_cpp_lib.dir/sam.cpp.o
make[2]: *** No rule to make target `/tempdeltavalue/Desktop/onnxruntime-osx-universal2-1.15.1/lib/libonnxruntime.dylib', needed by `libsam_cpp_lib.dylib'.  Stop.
make[1]: *** [CMakeFiles/sam_cpp_lib.dir/all] Error 2
make: *** [all] Error 2

**Comment by ryouchinsa** [comment]
This is our CMakeLists.txt and the folder structure.
In our environment, `cmake --build build` works.
```
cmake_minimum_required(VERSION 3.21)
set(CMAKE_CXX_STANDARD 17)
project(SamCPP)
find_package(OpenCV CONFIG REQUIRED)

add_library(sam_cpp_lib SHARED sam.h sam.cpp)
target_include_directories(
  sam_cpp_lib PUBLIC 
  /Users/ryo/Downloads/onnxruntime-osx-universal2-1.15.1/include
)
target_link_libraries(
  sam_cpp_lib PUBLIC
  /Users/ryo/Downloads/onnxruntime-osx-universal2-1.15.1/lib/libonnxruntime.dylib
  ${OpenCV_LIBS}
)

add_executable(sam_cpp_test test.cpp)
target_link_libraries(
  sam_cpp_test PRIVATE
  sam_cpp_lib
)
```

![スクリーンショット 2023-09-15 21 36 44](https://github.com/ryouchinsa/sam-cpp-macos/assets/1954306/ca228d8f-cecc-4bae-9567-b134f494e919)

**Comment by tempdeltavalue** [comment]
@ryouchinsa hmmm... thanks for your reply

<img width="350" alt="Screenshot 2023-09-15 at 23 12 49" src="https://github.com/ryouchinsa/sam-cpp-macos/assets/36921178/00149cd8-535d-45bd-852f-31672e9a8176">
<img width="572" alt="Screenshot 2023-09-15 at 23 12 59" src="https://github.com/ryouchinsa/sam-cpp-macos/assets/36921178/e5258251-72ed-434b-9aff-95d51e326b0e">

**Comment by tempdeltavalue** [comment]
@ryouchinsa Hmm.. thanks of your reply 
<img width="572" alt="Screenshot 2023-09-15 at 23 12 59" src="https://github.com/ryouchinsa/sam-cpp-macos/assets/36921178/fa064d51-2d29-4d40-983a-4e1b12351892">
<img width="350" alt="Screenshot 2023-09-15 at 23 12 49" src="https://github.com/ryouchinsa/sam-cpp-macos/assets/36921178/74da8939-0ab3-47fd-96d3-f84be418ac7e">

log with invocations 
Change Dir: '/Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build'

Run Build Command(s): /usr/local/Cellar/cmake/3.27.4/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile
/usr/local/Cellar/cmake/3.27.4/bin/cmake -S/Users/tempdeltavalue/Desktop/test/sam-cpp-macos -B/Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.27.4/bin/cmake -E cmake_progress_start /Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build/CMakeFiles /Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build//CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/sam_cpp_lib.dir/build.make CMakeFiles/sam_cpp_lib.dir/depend
cd /Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build && /usr/local/Cellar/cmake/3.27.4/bin/cmake -E cmake_depends "Unix Makefiles" /Users/tempdeltavalue/Desktop/test/sam-cpp-macos /Users/tempdeltavalue/Desktop/test/sam-cpp-macos /Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build /Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build /Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build/CMakeFiles/sam_cpp_lib.dir/DependInfo.cmake "--color="
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/sam_cpp_lib.dir/build.make CMakeFiles/sam_cpp_lib.dir/build
[ 25%] Building CXX object CMakeFiles/sam_cpp_lib.dir/sam.cpp.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -Dsam_cpp_lib_EXPORTS -I/Users/tempdeltavalue/Desktop/test/onnxruntime-osx-universal2-1.15.1/include -isystem /usr/local/Cellar/opencv/4.8.0_5/include/opencv4 -std=gnu++17 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -fPIC -MD -MT CMakeFiles/sam_cpp_lib.dir/sam.cpp.o -MF CMakeFiles/sam_cpp_lib.dir/sam.cpp.o.d -o CMakeFiles/sam_cpp_lib.dir/sam.cpp.o -c /Users/tempdeltavalue/Desktop/test/sam-cpp-macos/sam.cpp
[ 50%] Linking CXX shared library libsam_cpp_lib.dylib
/usr/local/Cellar/cmake/3.27.4/bin/cmake -E cmake_link_script CMakeFiles/sam_cpp_lib.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -dynamiclib -Wl,-headerpad_max_install_names -o libsam_cpp_lib.dylib -install_name @rpath/libsam_cpp_lib.dylib CMakeFiles/sam_cpp_lib.dir/sam.cpp.o  -Wl,-rpath,/Users/tempdeltavalue/Desktop/test/onnxruntime-osx-universal2-1.15.1/lib -Wl,-rpath,/usr/local/lib -lPUBLIC/Users /Users/tempdeltavalue/Desktop/test/onnxruntime-osx-universal2-1.15.1/lib/libonnxruntime.dylib /usr/local/lib/libopencv_gapi.4.8.0.dylib /usr/local/lib/libopencv_stitching.4.8.0.dylib /usr/local/lib/libopencv_alphamat.4.8.0.dylib /usr/local/lib/libopencv_aruco.4.8.0.dylib /usr/local/lib/libopencv_bgsegm.4.8.0.dylib /usr/local/lib/libopencv_bioinspired.4.8.0.dylib /usr/local/lib/libopencv_ccalib.4.8.0.dylib /usr/local/lib/libopencv_dnn_objdetect.4.8.0.dylib /usr/local/lib/libopencv_dnn_superres.4.8.0.dylib /usr/local/lib/libopencv_dpm.4.8.0.dylib /usr/local/lib/libopencv_face.4.8.0.dylib /usr/local/lib/libopencv_freetype.4.8.0.dylib /usr/local/lib/libopencv_fuzzy.4.8.0.dylib /usr/local/lib/libopencv_hfs.4.8.0.dylib /usr/local/lib/libopencv_img_hash.4.8.0.dylib /usr/local/lib/libopencv_intensity_transform.4.8.0.dylib /usr/local/lib/libopencv_line_descriptor.4.8.0.dylib /usr/local/lib/libopencv_mcc.4.8.0.dylib /usr/local/lib/libopencv_quality.4.8.0.dylib /usr/local/lib/libopencv_rapid.4.8.0.dylib /usr/local/lib/libopencv_reg.4.8.0.dylib /usr/local/lib/libopencv_rgbd.4.8.0.dylib /usr/local/lib/libopencv_saliency.4.8.0.dylib /usr/local/lib/libopencv_sfm.4.8.0.dylib /usr/local/lib/libopencv_stereo.4.8.0.dylib /usr/local/lib/libopencv_structured_light.4.8.0.dylib /usr/local/lib/libopencv_superres.4.8.0.dylib /usr/local/lib/libopencv_surface_matching.4.8.0.dylib /usr/local/lib/libopencv_tracking.4.8.0.dylib /usr/local/lib/libopencv_videostab.4.8.0.dylib /usr/local/lib/libopencv_viz.4.8.0.dylib /usr/local/lib/libopencv_wechat_qrcode.4.8.0.dylib /usr/local/lib/libopencv_xfeatures2d.4.8.0.dylib /usr/local/lib/libopencv_xobjdetect.4.8.0.dylib /usr/local/lib/libopencv_xphoto.4.8.0.dylib /usr/local/lib/libopencv_shape.4.8.0.dylib /usr/local/lib/libopencv_highgui.4.8.0.dylib /usr/local/lib/libopencv_datasets.4.8.0.dylib /usr/local/lib/libopencv_plot.4.8.0.dylib /usr/local/lib/libopencv_text.4.8.0.dylib /usr/local/lib/libopencv_ml.4.8.0.dylib /usr/local/lib/libopencv_phase_unwrapping.4.8.0.dylib /usr/local/lib/libopencv_optflow.4.8.0.dylib /usr/local/lib/libopencv_ximgproc.4.8.0.dylib /usr/local/lib/libopencv_video.4.8.0.dylib /usr/local/lib/libopencv_videoio.4.8.0.dylib /usr/local/lib/libopencv_imgcodecs.4.8.0.dylib /usr/local/lib/libopencv_objdetect.4.8.0.dylib /usr/local/lib/libopencv_calib3d.4.8.0.dylib /usr/local/lib/libopencv_dnn.4.8.0.dylib /usr/local/lib/libopencv_features2d.4.8.0.dylib /usr/local/lib/libopencv_flann.4.8.0.dylib /usr/local/lib/libopencv_photo.4.8.0.dylib /usr/local/lib/libopencv_imgproc.4.8.0.dylib /usr/local/lib/libopencv_core.4.8.0.dylib 
ld: library not found for -lPUBLIC/Users
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libsam_cpp_lib.dylib] Error 1
make[1]: *** [CMakeFiles/sam_cpp_lib.dir/all] Error 2
make: *** [all] Error 2

**Comment by tempdeltavalue** [comment]
@ryouchinsa Thanks for a reply 

<img width="357" alt="Screenshot 2023-09-15 at 23 24 15" src="https://github.com/ryouchinsa/sam-cpp-macos/ass
<img width="572" alt="Screenshot 2023-09-15 at 23 12 59" src="https://github.com/ryouchinsa/sam-cpp-macos/assets/36921178/a8504cf0-3605-473e-a7a3-b2d98ad94242">
ets/36921178/b8d93b5c-fbe0-457c-9790-cdcc2968512c">

Change Dir: '/Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build'

Run Build Command(s): /usr/local/Cellar/cmake/3.27.4/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile
/usr/local/Cellar/cmake/3.27.4/bin/cmake -S/Users/tempdeltavalue/Desktop/test/sam-cpp-macos -B/Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.27.4/bin/cmake -E cmake_progress_start /Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build/CMakeFiles /Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build//CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/sam_cpp_lib.dir/build.make CMakeFiles/sam_cpp_lib.dir/depend
cd /Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build && /usr/local/Cellar/cmake/3.27.4/bin/cmake -E cmake_depends "Unix Makefiles" /Users/tempdeltavalue/Desktop/test/sam-cpp-macos /Users/tempdeltavalue/Desktop/test/sam-cpp-macos /Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build /Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build /Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build/CMakeFiles/sam_cpp_lib.dir/DependInfo.cmake "--color="
Dependencies file "CMakeFiles/sam_cpp_lib.dir/sam.cpp.o.d" is newer than depends file "/Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build/CMakeFiles/sam_cpp_lib.dir/compiler_depend.internal".
Consolidate compiler generated dependencies of target sam_cpp_lib
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/sam_cpp_lib.dir/build.make CMakeFiles/sam_cpp_lib.dir/build
[ 25%] Linking CXX shared library libsam_cpp_lib.dylib
/usr/local/Cellar/cmake/3.27.4/bin/cmake -E cmake_link_script CMakeFiles/sam_cpp_lib.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -dynamiclib -Wl,-headerpad_max_install_names -o libsam_cpp_lib.dylib -install_name @rpath/libsam_cpp_lib.dylib CMakeFiles/sam_cpp_lib.dir/sam.cpp.o  -Wl,-rpath,/Users/tempdeltavalue/Desktop/test/onnxruntime-osx-universal2-1.15.1/lib -Wl,-rpath,/usr/local/lib -lPUBLIC/Users /Users/tempdeltavalue/Desktop/test/onnxruntime-osx-universal2-1.15.1/lib/libonnxruntime.dylib /usr/local/lib/libopencv_gapi.4.8.0.dylib /usr/local/lib/libopencv_stitching.4.8.0.dylib /usr/local/lib/libopencv_alphamat.4.8.0.dylib /usr/local/lib/libopencv_aruco.4.8.0.dylib /usr/local/lib/libopencv_bgsegm.4.8.0.dylib /usr/local/lib/libopencv_bioinspired.4.8.0.dylib /usr/local/lib/libopencv_ccalib.4.8.0.dylib /usr/local/lib/libopencv_dnn_objdetect.4.8.0.dylib /usr/local/lib/libopencv_dnn_superres.4.8.0.dylib /usr/local/lib/libopencv_dpm.4.8.0.dylib /usr/local/lib/libopencv_face.4.8.0.dylib /usr/local/lib/libopencv_freetype.4.8.0.dylib /usr/local/lib/libopencv_fuzzy.4.8.0.dylib /usr/local/lib/libopencv_hfs.4.8.0.dylib /usr/local/lib/libopencv_img_hash.4.8.0.dylib /usr/local/lib/libopencv_intensity_transform.4.8.0.dylib /usr/local/lib/libopencv_line_descriptor.4.8.0.dylib /usr/local/lib/libopencv_mcc.4.8.0.dylib /usr/local/lib/libopencv_quality.4.8.0.dylib /usr/local/lib/libopencv_rapid.4.8.0.dylib /usr/local/lib/libopencv_reg.4.8.0.dylib /usr/local/lib/libopencv_rgbd.4.8.0.dylib /usr/local/lib/libopencv_saliency.4.8.0.dylib /usr/local/lib/libopencv_sfm.4.8.0.dylib /usr/local/lib/libopencv_stereo.4.8.0.dylib /usr/local/lib/libopencv_structured_light.4.8.0.dylib /usr/local/lib/libopencv_superres.4.8.0.dylib /usr/local/lib/libopencv_surface_matching.4.8.0.dylib /usr/local/lib/libopencv_tracking.4.8.0.dylib /usr/local/lib/libopencv_videostab.4.8.0.dylib /usr/local/lib/libopencv_viz.4.8.0.dylib /usr/local/lib/libopencv_wechat_qrcode.4.8.0.dylib /usr/local/lib/libopencv_xfeatures2d.4.8.0.dylib /usr/local/lib/libopencv_xobjdetect.4.8.0.dylib /usr/local/lib/libopencv_xphoto.4.8.0.dylib /usr/local/lib/libopencv_shape.4.8.0.dylib /usr/local/lib/libopencv_highgui.4.8.0.dylib /usr/local/lib/libopencv_datasets.4.8.0.dylib /usr/local/lib/libopencv_plot.4.8.0.dylib /usr/local/lib/libopencv_text.4.8.0.dylib /usr/local/lib/libopencv_ml.4.8.0.dylib /usr/local/lib/libopencv_phase_unwrapping.4.8.0.dylib /usr/local/lib/libopencv_optflow.4.8.0.dylib /usr/local/lib/libopencv_ximgproc.4.8.0.dylib /usr/local/lib/libopencv_video.4.8.0.dylib /usr/local/lib/libopencv_videoio.4.8.0.dylib /usr/local/lib/libopencv_imgcodecs.4.8.0.dylib /usr/local/lib/libopencv_objdetect.4.8.0.dylib /usr/local/lib/libopencv_calib3d.4.8.0.dylib /usr/local/lib/libopencv_dnn.4.8.0.dylib /usr/local/lib/libopencv_features2d.4.8.0.dylib /usr/local/lib/libopencv_flann.4.8.0.dylib /usr/local/lib/libopencv_photo.4.8.0.dylib /usr/local/lib/libopencv_imgproc.4.8.0.dylib /usr/local/lib/libopencv_core.4.8.0.dylib 
ld: library not found for -lPUBLIC/Users
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libsam_cpp_lib.dylib] Error 1
make[1]: *** [CMakeFiles/sam_cpp_lib.dir/all] Error 2
make: *** [all] Error 2

**Comment by tempdeltavalue** [comment]
Thanks for a reply 

<img width="350" alt="Screenshot 2023-09-15 at 23 12 49" src="https://github.com/ryouchinsa/sam-cpp-macos/assets/36921178/f526adb9-46ef-4dbc-baa8-4cc8160753f9">
<img width="572" alt="Screenshot 2023-09-15 at 23 12 59" src="https://github.com/ryouchinsa/sam-cpp-macos/assets/36921178/35b1effd-b693-437a-b122-6715c02681cb">

cmake list 

cmake_minimum_required(VERSION 3.21)
set(CMAKE_CXX_STANDARD 17)
project(SamCPP)
find_package(OpenCV CONFIG REQUIRED)

add_library(sam_cpp_lib SHARED sam.h sam.cpp)
target_include_directories(
  sam_cpp_lib PUBLIC 
  /Users/tempdeltavalue/Desktop/test/onnxruntime-osx-universal2-1.15.1/include
)
target_link_libraries(
  sam_cpp_lib PUBLIC/Users
  /Users/tempdeltavalue/Desktop/test/onnxruntime-osx-universal2-1.15.1/lib/libonnxruntime.dylib
  ${OpenCV_LIBS}
)

add_executable(sam_cpp_test test.cpp)
target_link_libraries(
  sam_cpp_test PRIVATE
  sam_cpp_lib
)


logs

Change Dir: '/Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build'

Run Build Command(s): /usr/local/Cellar/cmake/3.27.4/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile
/usr/local/Cellar/cmake/3.27.4/bin/cmake -S/Users/tempdeltavalue/Desktop/test/sam-cpp-macos -B/Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.27.4/bin/cmake -E cmake_progress_start /Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build/CMakeFiles /Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build//CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/sam_cpp_lib.dir/build.make CMakeFiles/sam_cpp_lib.dir/depend
cd /Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build && /usr/local/Cellar/cmake/3.27.4/bin/cmake -E cmake_depends "Unix Makefiles" /Users/tempdeltavalue/Desktop/test/sam-cpp-macos /Users/tempdeltavalue/Desktop/test/sam-cpp-macos /Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build /Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build /Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build/CMakeFiles/sam_cpp_lib.dir/DependInfo.cmake "--color="
Dependencies file "CMakeFiles/sam_cpp_lib.dir/sam.cpp.o.d" is newer than depends file "/Users/tempdeltavalue/Desktop/test/sam-cpp-macos/build/CMakeFiles/sam_cpp_lib.dir/compiler_depend.internal".
Consolidate compiler generated dependencies of target sam_cpp_lib
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/sam_cpp_lib.dir/build.make CMakeFiles/sam_cpp_lib.dir/build
[ 25%] Linking CXX shared library libsam_cpp_lib.dylib
/usr/local/Cellar/cmake/3.27.4/bin/cmake -E cmake_link_script CMakeFiles/sam_cpp_lib.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -dynamiclib -Wl,-headerpad_max_install_names -o libsam_cpp_lib.dylib -install_name @rpath/libsam_cpp_lib.dylib CMakeFiles/sam_cpp_lib.dir/sam.cpp.o  -Wl,-rpath,/Users/tempdeltavalue/Desktop/test/onnxruntime-osx-universal2-1.15.1/lib -Wl,-rpath,/usr/local/lib -lPUBLIC/Users /Users/tempdeltavalue/Desktop/test/onnxruntime-osx-universal2-1.15.1/lib/libonnxruntime.dylib /usr/local/lib/libopencv_gapi.4.8.0.dylib /usr/local/lib/libopencv_stitching.4.8.0.dylib /usr/local/lib/libopencv_alphamat.4.8.0.dylib /usr/local/lib/libopencv_aruco.4.8.0.dylib /usr/local/lib/libopencv_bgsegm.4.8.0.dylib /usr/local/lib/libopencv_bioinspired.4.8.0.dylib /usr/local/lib/libopencv_ccalib.4.8.0.dylib /usr/local/lib/libopencv_dnn_objdetect.4.8.0.dylib /usr/local/lib/libopencv_dnn_superres.4.8.0.dylib /usr/local/lib/libopencv_dpm.4.8.0.dylib /usr/local/lib/libopencv_face.4.8.0.dylib /usr/local/lib/libopencv_freetype.4.8.0.dylib /usr/local/lib/libopencv_fuzzy.4.8.0.dylib /usr/local/lib/libopencv_hfs.4.8.0.dylib /usr/local/lib/libopencv_img_hash.4.8.0.dylib /usr/local/lib/libopencv_intensity_transform.4.8.0.dylib /usr/local/lib/libopencv_line_descriptor.4.8.0.dylib /usr/local/lib/libopencv_mcc.4.8.0.dylib /usr/local/lib/libopencv_quality.4.8.0.dylib /usr/local/lib/libopencv_rapid.4.8.0.dylib /usr/local/lib/libopencv_reg.4.8.0.dylib /usr/local/lib/libopencv_rgbd.4.8.0.dylib /usr/local/lib/libopencv_saliency.4.8.0.dylib /usr/local/lib/libopencv_sfm.4.8.0.dylib /usr/local/lib/libopencv_stereo.4.8.0.dylib /usr/local/lib/libopencv_structured_light.4.8.0.dylib /usr/local/lib/libopencv_superres.4.8.0.dylib /usr/local/lib/libopencv_surface_matching.4.8.0.dylib /usr/local/lib/libopencv_tracking.4.8.0.dylib /usr/local/lib/libopencv_videostab.4.8.0.dylib /usr/local/lib/libopencv_viz.4.8.0.dylib /usr/local/lib/libopencv_wechat_qrcode.4.8.0.dylib /usr/local/lib/libopencv_xfeatures2d.4.8.0.dylib /usr/local/lib/libopencv_xobjdetect.4.8.0.dylib /usr/local/lib/libopencv_xphoto.4.8.0.dylib /usr/local/lib/libopencv_shape.4.8.0.dylib /usr/local/lib/libopencv_highgui.4.8.0.dylib /usr/local/lib/libopencv_datasets.4.8.0.dylib /usr/local/lib/libopencv_plot.4.8.0.dylib /usr/local/lib/libopencv_text.4.8.0.dylib /usr/local/lib/libopencv_ml.4.8.0.dylib /usr/local/lib/libopencv_phase_unwrapping.4.8.0.dylib /usr/local/lib/libopencv_optflow.4.8.0.dylib /usr/local/lib/libopencv_ximgproc.4.8.0.dylib /usr/local/lib/libopencv_video.4.8.0.dylib /usr/local/lib/libopencv_videoio.4.8.0.dylib /usr/local/lib/libopencv_imgcodecs.4.8.0.dylib /usr/local/lib/libopencv_objdetect.4.8.0.dylib /usr/local/lib/libopencv_calib3d.4.8.0.dylib /usr/local/lib/libopencv_dnn.4.8.0.dylib /usr/local/lib/libopencv_features2d.4.8.0.dylib /usr/local/lib/libopencv_flann.4.8.0.dylib /usr/local/lib/libopencv_photo.4.8.0.dylib /usr/local/lib/libopencv_imgproc.4.8.0.dylib /usr/local/lib/libopencv_core.4.8.0.dylib 
ld: library not found for -lPUBLIC/Users
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libsam_cpp_lib.dylib] Error 1
make[1]: *** [CMakeFiles/sam_cpp_lib.dir/all] Error 2
make: *** [all] Error 2

**Comment by ryouchinsa** [comment]
For the SAM feature, please use Edit -> [Create polygon using SAM](https://rectlabel.com/edit#create_sam) menu.

**Comment by ryouchinsa** [comment]
For the build error, check the OpenCV_INCLUDE_DIRS and OpenCV_LIBS are correct.
Adding message() after find_package() in CMakeLists.txt, you can show those paths.

```
cmake_minimum_required(VERSION 3.21)
set(CMAKE_CXX_STANDARD 17)
project(SamCPP)
find_package(OpenCV CONFIG REQUIRED)

message(STATUS "OpenCV_INCLUDE_DIRS = ${OpenCV_INCLUDE_DIRS}")
message(STATUS "OpenCV_LIBS = ${OpenCV_LIBS}")

add_library(sam_cpp_lib SHARED sam.h sam.cpp)
target_include_directories(
  sam_cpp_lib PUBLIC 
  /Users/ryo/Downloads/onnxruntime-osx-universal2-1.15.1/include
)
target_link_libraries(
  sam_cpp_lib PUBLIC
  /Users/ryo/Downloads/onnxruntime-osx-universal2-1.15.1/lib/libonnxruntime.dylib
  ${OpenCV_LIBS}
)

add_executable(sam_cpp_test test.cpp)
target_link_libraries(
  sam_cpp_test PRIVATE
  sam_cpp_lib
)
```
This is our terminal printed messages when `cmake -S . -B build`.

```
-- The C compiler identification is AppleClang 14.0.3.14030022
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenCV: /opt/homebrew/Cellar/opencv/4.8.0_6 (found version "4.8.0") 
-- OpenCV_INCLUDE_DIRS = /opt/homebrew/Cellar/opencv/4.8.0_6/include/opencv4
-- OpenCV_LIBS = opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_gapi;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_stitching;opencv_video;opencv_videoio;opencv_alphamat;opencv_aruco;opencv_bgsegm;opencv_bioinspired;opencv_ccalib;opencv_datasets;opencv_dnn_objdetect;opencv_dnn_superres;opencv_dpm;opencv_face;opencv_freetype;opencv_fuzzy;opencv_hfs;opencv_img_hash;opencv_intensity_transform;opencv_line_descriptor;opencv_mcc;opencv_optflow;opencv_phase_unwrapping;opencv_plot;opencv_quality;opencv_rapid;opencv_reg;opencv_rgbd;opencv_saliency;opencv_sfm;opencv_shape;opencv_stereo;opencv_structured_light;opencv_superres;opencv_surface_matching;opencv_text;opencv_tracking;opencv_videostab;opencv_viz;opencv_wechat_qrcode;opencv_xfeatures2d;opencv_ximgproc;opencv_xobjdetect;opencv_xphoto
-- Configuring done (7.9s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/ryo/Downloads/sam-cpp-macos/build
```

**Comment by ryouchinsa** [comment]
Thanks for your detailed feedback.

In our macOS app RectLabel, we are using the universal OpenCV framework.
https://github.com/opencv/opencv/issues/18049

The purpose of this repository is not sharing how to use OpenCV in your macOS or iOS apps.
We assume that you can build and run your image processing code using the OpenCV framework.

Using the sam-cpp-macos code, you can run the Segment Anything Model feature using C++ code.
The usability is the same as running the image processing code using the OpenCV framework in your apps.

In July 2023, we stared implementing Segment Anything Model feature on RectLabel.
If we had this sam-cpp-macos code at that time, we could release the update more than 2 weeks earlier.

Please let us know your opinion.

**Comment by tempdeltavalue** [comment]
Hi, just want you to know that I took this macOS cpp code and put it inside iOS app and everything working (thank you a lot for that)

fyi
https://github.com/tempdeltavalue/SceneKitTest

**Comment by ryouchinsa** [comment]
Thanks for letting us know that you could run Segment Anything Model on your iOS app. Other users will be interested in your iOS code.
