### ISSUE TITLE
Can this be used on iOS as well or on MacOS?

### ISSUE THREAD

**Issue by roimulia2** [ryouchinsa/sam-cpp-macos#2]
Hey!

Can this be used on iOS as well or on MacOS?

Thanks!

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.

**Comment by ryouchinsa** [comment]
We can introduce [SegmentAnythingMobile](https://github.com/AlessandroToschi/SegmentAnythingMobile).
"There are plenty of iOS apps that perform magic erasing but usually, it is a premium feature. So, I challenged myself to implement it."

https://github.com/ryouchinsa/sam-cpp-macos/assets/1954306/77b25e68-0d3d-4ce0-9ae0-efaa19a366fa
