### ISSUE TITLE
SAM2.1

### ISSUE THREAD

**Issue by sctrueew** [ryouchinsa/sam-cpp-macos#7]
Hi, thanks for your work. Is it possible to support SAM2.1?

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Yes, we are supporting the SAM 2.1 models.

Install [Segment Anything Model 2](https://github.com/facebookresearch/sam2) and download checkpoints.

![checkpoints](https://github.com/user-attachments/assets/0a905f19-6cb8-4231-a355-df6b1e8f1ab0)

Copy yaml files in sam2/configs/sam2.1 to sam2.

![configs](https://github.com/user-attachments/assets/39827d2f-76ba-4904-bc59-9e0716af6cda)

Put [export_onnx.py](https://github.com/ryouchinsa/sam-cpp-macos/blob/master/export_onnx.py) and david-tomaseti-Vw2HZQ1FGjU-unsplash.jpg to the root folder.

![export](https://github.com/user-attachments/assets/0fc7dcce-8f38-403b-b84e-bb38fea0eeca)

To export an ONNX model.

```bash
python export_onnx.py --mode export
```

To check how the ONNX model works.

```bash
python export_onnx.py --mode import
```

You can download exported SAM 2.1 ONNX models.
- [SAM2 Tiny](https://huggingface.co/rectlabel/segment-anything-onnx-models/resolve/main/sam2_tiny.zip)
- [SAM2 Small](https://huggingface.co/rectlabel/segment-anything-onnx-models/resolve/main/sam2_small.zip)
- [SAM2 BasePlus](https://huggingface.co/rectlabel/segment-anything-onnx-models/resolve/main/sam2_base_plus.zip)
- [SAM2 Large](https://huggingface.co/rectlabel/segment-anything-onnx-models/resolve/main/sam2_large.zip)

**Comment by sctrueew** [comment]
That sounds great. I will take a look at it.

**Comment by ryouchinsa** [comment]
To be clear that we are supporting SAM 2.1, we updated our document.
